import { z } from "zod";
import { AppStateSchema } from "../types/schema";
import { DEFAULT_APP_STATE } from "../types/constants";

export const TRAVEL_TEMPLATE: z.infer<typeof AppStateSchema> = {
  ...DEFAULT_APP_STATE,
  aspectRatio: "9:16",
  items: [
    {
      id: "1",
      duration: 120,
      nodes: [
        {
          id: "1",
          type: "text",
          text: "Spain Calling 2016",
          fontSize: 50,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          x: 0,
          y: 50,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "left",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },
        {
          id: "2",
          type: "text",
          text: "Alcázar of Seville, Seville",
          fontSize: 30,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          x: 0,
          y: 140,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "left",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },

        {
          id: "3",
          type: "text",
          text: "Channeling my inner royalty\nin the stunning arches of the\nAlcázar of Seville! 🏰✨",
          fontSize: 30,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          layout: "center",
          textAlign: "center",
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          stroke: {
            enabled: true,
            color: "#000000",
            width: 5,
            join: "round",
          },
          x: 140,
          y: 640,
        },

        {
          id: "4",
          type: "text",
          text: "#AlcazarMagic",
          fontSize: 24,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          x: 0,
          y: 900,
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 20,
          },
        },

        {
          id: "6wete",
          type: "image",
          url: "https://firebasestorage.googleapis.com/v0/b/drawing-87071.appspot.com/o/width_8000.png?alt=media&token=e1e7e22f-2749-49aa-bb8b-c8af307c3cda",

          x: 360,
          y: 900,
          width: 300,
          height: 300,
          opacity: 1,
          scale: 1,
          rotation: 0,
          objectFit: "contain",
          cornerRadius: 0,
        },
      ],
      media: {
        id: "1",
        type: "image",
        url: "https://konvajs.org/assets/darth-vader.jpg",
        transitionConfig: {
          type: "slide",
          duration: 10,
          direction: "from-right",
        },
      },
    },

    {
      id: "2",
      duration: 90,
      nodes: [
        {
          id: "1",
          type: "text",
          text: "Spain Calling 2016",
          fontSize: 50,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          x: 0,
          y: 50,
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },
        {
          id: "2",
          type: "text",
          text: "National Art Museum of Catalonia,\nBarcelona",
          fontSize: 30,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "left",
          x: 0,
          y: 140,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "left",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },

        {
          id: "3",
          type: "text",
          text: "Caught in the magic of\nBarcelona with this\nspectacular backdrop! love\nin the air. 🎨💞",
          fontSize: 24,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          layout: "center",
          textAlign: "left",
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          stroke: {
            enabled: true,
            color: "#000000",
            width: 5,
            join: "round",
          },
          x: 0,
          y: 700,
        },

        {
          id: "4",
          type: "text",
          text: "#BarcelonaMoments",
          fontSize: 24,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 0,
          y: 900,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 20,
          },
        },

        {
          id: "6wete",
          type: "image",
          url: "https://firebasestorage.googleapis.com/v0/b/drawing-87071.appspot.com/o/width_8000.png?alt=media&token=e1e7e22f-2749-49aa-bb8b-c8af307c3cda",

          x: 360,
          y: 900,
          width: 300,
          height: 300,
          opacity: 1,
          scale: 1,
          rotation: 0,
          objectFit: "contain",
          cornerRadius: 0,
        },
      ],
      media: {
        id: "1",
        type: "image",
        url: "https://konvajs.org/assets/darth-vader.jpg",
        transitionConfig: {
          type: "slide",
          duration: 10,
          direction: "from-right",
        },
      },
    },

    {
      id: "3",
      duration: 90,
      nodes: [
        {
          id: "1",
          type: "text",
          text: "Spain Calling 2016",
          fontSize: 50,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          x: 0,
          y: 50,
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },
        {
          id: "2",
          type: "text",
          text: "Mirador de San Nicolás,\nAlbaicín, Granada",
          fontSize: 30,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "left",
          x: 0,
          y: 140,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "left",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },

        {
          id: "3",
          type: "text",
          text: "Sometimes you just need a\nmoment to take it all in.\nGranada, you're a dream!",
          fontSize: 24,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          layout: "center",
          textAlign: "left",
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          stroke: {
            enabled: true,
            color: "#000000",
            width: 5,
            join: "round",
          },
          x: 0,
          y: 700,
        },

        {
          id: "4",
          type: "text",
          text: "#AndalusianViews",
          fontSize: 24,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 0,
          y: 900,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 20,
          },
        },

        {
          id: "6wete",
          type: "image",
          url: "https://firebasestorage.googleapis.com/v0/b/drawing-87071.appspot.com/o/width_8000.png?alt=media&token=e1e7e22f-2749-49aa-bb8b-c8af307c3cda",

          x: 360,
          y: 900,
          width: 300,
          height: 300,
          opacity: 1,
          scale: 1,
          rotation: 0,
          objectFit: "contain",
          cornerRadius: 0,
        },
      ],
      media: {
        id: "1",
        type: "image",
        url: "https://konvajs.org/assets/darth-vader.jpg",
        transitionConfig: {
          type: "slide",
          duration: 10,
          direction: "from-right",
        },
      },
    },

    {
      id: "4",
      duration: 90,
      nodes: [
        {
          id: "1",
          type: "text",
          text: "Spain Calling 2016",
          fontSize: 50,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          x: 0,
          y: 50,
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },
        {
          id: "2",
          type: "text",
          text: "Plaza in Albaicín, Granada",
          fontSize: 30,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "left",
          x: 0,
          y: 140,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "left",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },

        {
          id: "3",
          type: "text",
          text: "Strolling through Granada's\ncharming plazas and loving\nevery step. 🚶‍♀️",
          fontSize: 24,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          layout: "center",
          textAlign: "left",
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          stroke: {
            enabled: true,
            color: "#000000",
            width: 5,
            join: "round",
          },
          x: 0,
          y: 700,
        },

        {
          id: "4",
          type: "text",
          text: "#GranadaCharm",
          fontSize: 24,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 0,
          y: 900,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 20,
          },
        },

        {
          id: "6wete",
          type: "image",
          url: "https://firebasestorage.googleapis.com/v0/b/drawing-87071.appspot.com/o/width_8000.png?alt=media&token=e1e7e22f-2749-49aa-bb8b-c8af307c3cda",

          x: 360,
          y: 900,
          width: 300,
          height: 300,
          opacity: 1,
          scale: 1,
          rotation: 0,
          objectFit: "contain",
          cornerRadius: 0,
        },
      ],
      media: {
        id: "1",
        type: "image",
        url: "https://konvajs.org/assets/darth-vader.jpg",
        transitionConfig: {
          type: "slide",
          duration: 10,
          direction: "from-right",
        },
      },
    },
    {
      id: "5",
      duration: 120,
      nodes: [
        {
          id: "1",
          type: "text",
          text: "Spain Calling 2016",
          fontSize: 50,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          x: 0,
          y: 50,

          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },
        {
          id: "2",
          type: "text",
          text: "Market street in Albaicín, Granada",
          fontSize: 30,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "left",
          x: 0,
          y: 140,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "left",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },

        {
          id: "3",
          type: "text",
          text: "Losing ourselves in Granada's\nvibrant souks and soaking up\nall the colors and flavors.",
          fontSize: 24,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          layout: "center",
          textAlign: "left",
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          stroke: {
            enabled: true,
            color: "#000000",
            width: 5,
            join: "round",
          },
          x: 0,
          y: 700,
        },

        {
          id: "4",
          type: "text",
          text: "#MarketAdventures",
          fontSize: 24,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 0,
          y: 900,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 20,
          },
        },

        {
          id: "6wete",
          type: "image",
          url: "https://firebasestorage.googleapis.com/v0/b/drawing-87071.appspot.com/o/width_8000.png?alt=media&token=e1e7e22f-2749-49aa-bb8b-c8af307c3cda",

          x: 360,
          y: 900,
          width: 300,
          height: 300,
          opacity: 1,
          scale: 1,
          rotation: 0,
          objectFit: "contain",
          cornerRadius: 0,
        },
      ],
      media: {
        id: "1",
        type: "image",
        url: "https://konvajs.org/assets/darth-vader.jpg",
        transitionConfig: {
          type: "slide",
          duration: 10,
          direction: "from-right",
        },
      },
    },
    {
      id: "6",
      duration: 90,
      nodes: [
        {
          id: "1",
          type: "text",
          text: "Spain Calling 2016",
          fontSize: 50,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          x: 0,
          y: 50,

          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },
        {
          id: "2",
          type: "text",
          text: "Albaicín, Granada",
          fontSize: 30,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "left",
          x: 0,
          y: 140,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "left",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },

        {
          id: "3",
          type: "text",
          text: "Getting lost (and loving it) in\nthe dreamy white lanes of\nAlbaicín, Granada! 🏞️",
          fontSize: 24,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          layout: "center",
          textAlign: "left",
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          stroke: {
            enabled: true,
            color: "#000000",
            width: 5,
            join: "round",
          },
          x: 0,
          y: 700,
        },

        {
          id: "4",
          type: "text",
          text: "#GranadaVibes",
          fontSize: 24,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 0,
          y: 900,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 20,
          },
        },

        {
          id: "6wete",
          type: "image",
          url: "https://firebasestorage.googleapis.com/v0/b/drawing-87071.appspot.com/o/width_8000.png?alt=media&token=e1e7e22f-2749-49aa-bb8b-c8af307c3cda",

          x: 360,
          y: 900,
          width: 300,
          height: 300,
          opacity: 1,
          scale: 1,
          rotation: 0,
          objectFit: "contain",
          cornerRadius: 0,
        },
      ],
      media: {
        id: "1",
        type: "image",
        url: "https://konvajs.org/assets/darth-vader.jpg",
        transitionConfig: {
          type: "slide",
          duration: 10,
          direction: "from-right",
        },
      },
    },
    {
      id: "7",
      duration: 90,
      nodes: [
        {
          id: "1",
          type: "text",
          text: "Spain Calling 2016",
          fontSize: 50,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          x: 0,
          y: 50,
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },
        {
          id: "2",
          type: "text",
          text: "National Art Museum of Catalonia,\nBarcelona",
          fontSize: 30,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#000000",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "left",
          x: 0,
          y: 140,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "left",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 0,
          },
        },

        {
          id: "3",
          type: "text",
          text: "Taking in the Barcelona vibes and golden sunlight outside the stunning MNAC with my favorite crew!",
          fontSize: 24,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          layout: "center",
          textAlign: "left",
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          stroke: {
            enabled: true,
            color: "#000000",
            width: 5,
            join: "round",
          },
          x: 0,
          y: 700,
        },

        {
          id: "4",
          type: "text",
          text: "#ChillinInBarcelona",
          fontSize: 24,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 0,
          y: 900,
          animationConfig: {
            type: "slide",
            duration: 30,
            animationDirection: "bottom",
            delay: 15,
          },
          backgroundConfig: {
            enabled: true,
            color: "#12c7d6",
            alpha: 1,
            paddingX: 10,
            paddingY: 10,
            cornerRadius: 20,
          },
        },

        {
          id: "6wete",
          type: "image",
          url: "https://firebasestorage.googleapis.com/v0/b/drawing-87071.appspot.com/o/width_8000.png?alt=media&token=e1e7e22f-2749-49aa-bb8b-c8af307c3cda",

          x: 360,
          y: 900,
          width: 300,
          height: 300,
          opacity: 1,
          scale: 1,
          rotation: 0,
          objectFit: "contain",
          cornerRadius: 0,
        },
      ],
      media: {
        id: "1",
        type: "image",
        url: "https://konvajs.org/assets/darth-vader.jpg",
        transitionConfig: {
          type: "slide",
          duration: 10,
          direction: "from-right",
        },
      },
    },
    {
      id: "8",
      duration: 111,
      nodes: [
        {
          id: "2",
          type: "text",
          text: "MADE WITH",
          fontSize: 44,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFFFFF",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "left",
          layout: "center",
          x: 240,
          y: 250,
        },
        {
          id: "245",
          type: "text",
          text: "LOVE \u2764\ufe0f ON",
          fontSize: 44,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFDE59",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "left",
          layout: "center",
          x: 240,
          y: 290,
        },

        {
          id: "3",
          type: "text",
          text: "HAPPINESTAPP.COM",
          fontSize: 44,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFDE59",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "left",
          animationConfig: {
            type: "rotate-in",
            duration: 60,
            animationDirection: "right",
          },

          x: 80,
          y: 700,
        },

        {
          id: "4",
          type: "text",
          text: "@HAPPINESTAPP",
          fontSize: 44,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#FFDE59",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          animationConfig: {
            type: "rotate-in",
            duration: 60,
            animationDirection: "right",
          },
          x: 140,
          y: 600,
        },

        {
          id: "instagram-icon",
          type: "image",
          url: "https://firebasestorage.googleapis.com/v0/b/drawing-87071.appspot.com/o/Instagram_icon.png?alt=media&token=c4339bb9-9fb6-49f2-beea-ad853bbfc122",
          x: 80,
          y: 600,
          width: 60,
          height: 60,
          opacity: 1,
          rotation: 0,
          scale: 1,
          objectFit: "contain",
          cornerRadius: 0,
          animationConfig: {
            type: "pop",
            duration: 15,
            delay: 15,
          },
        },

        {
          id: "5",
          type: "image",
          url: "https://firebasestorage.googleapis.com/v0/b/drawing-87071.appspot.com/o/width_8000.png?alt=media&token=e1e7e22f-2749-49aa-bb8b-c8af307c3cda",
          x: -100,
          y: 100,
          width: 800,
          height: 800,
          opacity: 1,
          scale: 1,
          rotation: 0,
          objectFit: "contain",
          cornerRadius: 0,
          animationConfig: {
            type: "pop",
            duration: 15,
            delay: 15,
          },
        },
        {
          id: "6",
          type: "image",
          url: "https://firebasestorage.googleapis.com/v0/b/drawing-87071.appspot.com/o/width_800.png?alt=media&token=a9097eb1-568a-4cc6-89fb-e29d6810ad2b",
          x: 0,
          y: 700,
          width: 600,
          height: 600,
          opacity: 1,
          scale: 1,
          rotation: 0,
          objectFit: "contain",
          cornerRadius: 0,
        },

        {
          id: "6wete",
          type: "image",
          url: "https://firebasestorage.googleapis.com/v0/b/drawing-87071.appspot.com/o/width_8000.png?alt=media&token=e1e7e22f-2749-49aa-bb8b-c8af307c3cda",
          x: 360,
          y: 900,
          width: 300,
          height: 300,
          opacity: 1,
          scale: 1,
          rotation: 0,
          objectFit: "contain",
          cornerRadius: 0,
        },
      ],
      media: {
        id: "1",
        type: "image",
        url: "https://media.giphy.com/media/3o72F7YT6s0EMFI0Za/giphy.gif",
      },
    },
  ],
};
