import { z } from "zod";
import { AppStateSchema } from "./schema";
export const COMPOSITION_ID = "maindemo";

export const DEFAULT_APP_STATE: z.infer<typeof AppStateSchema> = {
  aspectRatio: "16:9" as const,
  resolution: "1080p" as const,
  musicUrl:
    "https://firebasestorage.googleapis.com/v0/b/drawing-87071.appspot.com/o/upbeat-222611.mp3?alt=media&token=862ae384-709e-41ad-8324-31db62cae06a",
  musicVolume: 0.5,
  items: [
    {
      id: "1",
      nodes: [
        {
          id: "1",
          type: "text",
          animationConfig: {
            type: "typewriter",
            duration: 40,
          },
          text: "🔥✅🔥✅🔥✅🔥✅🔥✅",
          fontSize: 50,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#3498db",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 50,
          dropShadow: {
            enabled: true,
            color: "#000000",
            alpha: 0.8,
            blur: 6,
            angle: Math.PI / 4,
            distance: 8,
          },
          stroke: {
            enabled: true,
            color: "#2980b9",
            width: 3,
            join: "round",
          },
        },
        {
          id: "1-heading",
          type: "text",
          animationConfig: {
            type: "fade",
            duration: 30,
          },
          text: "Welcome to VideoAPI",
          fontSize: 70,
          fontFamily: "Montserrat",
          fontWeight: 900,
          fontColor: "#ffffff",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 150,
          dropShadow: {
            enabled: true,
            color: "#000000",
            alpha: 0.9,
            blur: 8,
            angle: Math.PI / 4,
            distance: 6,
          },
        },
        {
          id: "1-subheading",
          type: "text",
          animationConfig: {
            type: "slide",
            duration: 25,
            animationDirection: "bottom",
          },
          text: "Create amazing videos programmatically",
          fontSize: 30,
          fontFamily: "Roboto",
          fontWeight: 400,
          fontColor: "#ecf0f1",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 230,
        },
      ],
      media: {
        id: "1",
        type: "image",
        transitionConfig: {
          type: "wipe",
          direction: "from-left",
          duration: 40,
        },
        url: "https://konvajs.org/assets/yoda.jpg",
      },
      duration: 120,
    },
    {
      id: "2",
      nodes: [
        {
          id: "2",
          type: "text",
          animationConfig: {
            type: "fade",
            duration: 25,
          },
          text: "Wipe Transition\nfrom-top",
          fontSize: 50,
          fontFamily: "Roboto",
          fontWeight: 700,
          fontColor: "#e74c3c",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "right",
          x: 100,
          y: 100,
          dropShadow: {
            enabled: false,
            color: "#000000",
            alpha: 0.5,
            blur: 4,
            angle: Math.PI / 4,
            distance: 6,
          },
          stroke: {
            enabled: true,
            color: "#ffffff",
            width: 4,
            join: "bevel",
          },
        },
        {
          id: "2-hashtags",
          type: "text",
          animationConfig: {
            type: "pop",
            duration: 20,
          },
          text: "#videoapi #animations #transitions",
          fontSize: 24,
          fontFamily: "Roboto",
          fontWeight: 400,
          fontColor: "#ecf0f1",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "right",
          layout: "right",
          x: 100,
          y: 400,
        },
      ],
      media: {
        id: "2",
        type: "image",
        transitionConfig: {
          type: "wipe",
          direction: "from-top",
          duration: 25,
        },
        url: "https://konvajs.org/assets/darth-vader.jpg",
      },
      duration: 90,
    },
    {
      id: "3",
      nodes: [
        {
          id: "3",
          type: "text",
          animationConfig: {
            type: "slide",
            duration: 20,
            animationDirection: "left",
          },
          text: "Wipe Transition\nfrom-right",
          fontSize: 50,
          fontFamily: "Pacifico",
          fontWeight: 700,
          fontColor: "#f1c40f",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "left",
          x: 100,
          y: 150,
          fillGradient: {
            enabled: true,
            colors: ["#f1c40f", "#e67e22"],
            angle: 45,
          },
        },
        {
          id: "3-heading",
          type: "text",
          animationConfig: {
            type: "bounce",
            duration: 35,
            animationDirection: "top",
          },
          text: "AMAZING EFFECTS",
          fontSize: 60,
          fontFamily: "Oswald",
          fontWeight: 800,
          fontColor: "#ffffff",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 70,
          stroke: {
            enabled: true,
            color: "#34495e",
            width: 5,
            join: "round",
          },
        },
      ],
      media: {
        id: "3",
        type: "image",
        transitionConfig: {
          type: "wipe",
          direction: "from-right",
          duration: 35,
        },
        url: "https://konvajs.org/assets/lion.png",
      },
      duration: 110,
    },
    {
      id: "4",
      duration: 100,
      nodes: [
        {
          id: "4",
          type: "text",
          animationConfig: {
            type: "pop",
            duration: 15,
          },
          text: "Slide  Transition\nfrom-bottom",
          fontSize: 50,
          fontFamily: "Oswald",
          fontWeight: 700,
          fontColor: "#9b59b6",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 200,
          dropShadow: {
            enabled: true,
            color: "#34495e",
            alpha: 0.9,
            blur: 8,
            angle: Math.PI / 3,
            distance: 10,
          },
        },
        {
          id: "4-subheading",
          type: "text",
          animationConfig: {
            type: "fade",
            duration: 25,
          },
          text: "Easy to customize and implement",
          fontSize: 30,
          fontFamily: "Roboto",
          fontWeight: 400,
          fontColor: "#ecf0f1",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 280,
        },
        {
          id: "4-hashtags",
          type: "text",
          animationConfig: {
            type: "flash",
            duration: 30,
          },
          text: "#slideTransition #effects #videoapi",
          fontSize: 24,
          fontFamily: "Roboto",
          fontWeight: 400,
          fontColor: "#ecf0f1",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 440,
        },
      ],
      media: {
        id: "4",
        type: "image",
        transitionConfig: {
          type: "slide",
          direction: "from-bottom",
          duration: 45,
        },
        url: "https://konvajs.org/assets/yoda.jpg",
      },
    },
    {
      id: "5",
      duration: 100,
      nodes: [
        {
          id: "5",
          type: "text",
          animationConfig: {
            type: "flash",
            duration: 35,
          },
          text: "Fade Transition",
          fontSize: 50,
          fontFamily: "Dancing Script",
          fontWeight: 700,
          fontColor: "#2ecc71",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 250,
          stroke: {
            enabled: true,
            color: "#27ae60",
            width: 2,
            join: "miter",
          },
          dropShadow: {
            enabled: false,
            color: "#000000",
            alpha: 0.5,
            blur: 4,
            angle: Math.PI / 4,
            distance: 6,
          },
          backgroundConfig: {
            enabled: true,
            color: "#000000",
            alpha: 1,
            paddingX: 30,
            paddingY: 15,
            cornerRadius: 10,
            animationConfig: {
              type: "slide",
              duration: 30,
              animationDirection: "left",
            },
          },
        },
      ],
      media: {
        id: "5",
        type: "image",
        transitionConfig: {
          type: "fade",
          duration: 60,
        },
        url: "https://konvajs.org/assets/darth-vader.jpg",
      },
    },
    {
      id: "6",
      duration: 100,
      nodes: [
        {
          id: "6",
          type: "text",
          animationConfig: {
            type: "pulse",
            duration: 45,
          },
          text: "Star/Dissolve Transition",
          fontSize: 50,
          fontFamily: "Lato",
          fontWeight: 700,
          fontColor: "#1abc9c",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 300,
          fillGradient: {
            enabled: true,
            colors: ["#1abc9c", "#3498db"],
            angle: 90,
          },
          dropShadow: {
            enabled: true,
            color: "#000000",
            alpha: 0.5,
            blur: 4,
            angle: Math.PI / 6,
            distance: 6,
          },
        },
      ],
      media: {
        id: "6",
        type: "image",
        transitionConfig: {
          type: "wipe",
          direction: "from-bottom",
          duration: 30,
        },
        url: "https://konvajs.org/assets/yoda.jpg",
      },
    },
    {
      id: "7",
      duration: 100,
      nodes: [
        {
          id: "7",
          type: "text",
          animationConfig: {
            type: "bounce",
            duration: 30,
            animationDirection: "right",
          },
          text: "Wipe Transition\nfrom-bottom-right",
          fontSize: 50,
          fontFamily: "Playfair Display",
          fontWeight: 700,
          fontColor: "#ecf0f1",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 350,
          stroke: {
            enabled: true,
            color: "#34495e",
            width: 5,
            join: "round",
          },
          dropShadow: {
            enabled: true,
            color: "#2c3e50",
            alpha: 1,
            blur: 10,
            angle: Math.PI / 2,
            distance: 5,
          },
        },
      ],
      media: {
        id: "7",
        type: "image",
        transitionConfig: {
          type: "wipe",
          direction: "from-right",
          duration: 35,
        },
        url: "https://konvajs.org/assets/darth-vader.jpg",
      },
    },
    {
      id: "8",
      duration: 100,
      nodes: [
        {
          id: "8",
          type: "text",
          animationConfig: {
            type: "fade",
            duration: 30,
          },
          text: "Cute Kitten Demo",
          fontSize: 50,
          fontFamily: "Montserrat",
          fontWeight: 700,
          fontColor: "#ffffff",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 150,
          dropShadow: {
            enabled: true,
            color: "#000000",
            alpha: 0.8,
            blur: 6,
            angle: Math.PI / 4,
            distance: 8,
          },
        },
        {
          id: "8-heading",
          type: "text",
          animationConfig: {
            type: "typewriter",
            duration: 40,
          },
          text: "PLACEKITTEN API",
          fontSize: 70,
          fontFamily: "Oswald",
          fontWeight: 900,
          fontColor: "#ff6b6b",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 50,
          stroke: {
            enabled: true,
            color: "#ffffff",
            width: 4,
            join: "round",
          },
          backgroundConfig: {
            enabled: true,
            color: "#333333",
            alpha: 0.5,
            paddingX: 40,
            paddingY: 10,
            cornerRadius: 5,
          },
        },
        {
          id: "8-subheading",
          type: "text",
          animationConfig: {
            type: "slide",
            duration: 25,
            animationDirection: "bottom",
          },
          text: "Beautiful placeholder images for your projects",
          fontSize: 30,
          fontFamily: "Roboto",
          fontWeight: 400,
          fontColor: "#ffffff",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 230,
        },
        {
          id: "8-hashtags",
          type: "text",
          animationConfig: {
            type: "pop",
            duration: 20,
          },
          text: "#placekitten #cute #webdesign",
          fontSize: 24,
          fontFamily: "Roboto",
          fontWeight: 400,
          fontColor: "#ffffff",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          x: 100,
          y: 440,
        },
      ],
      media: {
        id: "8",
        type: "image",
        transitionConfig: {
          type: "fade",
          duration: 30,
        },
        url: "https://konvajs.org/assets/lion.png",
      },
    },
    {
      id: "9",
      duration: 100,
      nodes: [
        {
          id: "9",
          type: "text",
          animationConfig: {
            type: "slide",
            duration: 25,
            animationDirection: "left",
          },
          text: "More Kittens!",
          fontSize: 50,
          fontFamily: "Pacifico",
          fontWeight: 700,
          fontColor: "#f8e9a1",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "right",
          x: 100,
          y: 200,
          dropShadow: {
            enabled: true,
            color: "#000000",
            alpha: 0.7,
            blur: 5,
            angle: Math.PI / 6,
            distance: 6,
          },
        },
        {
          id: "9-heading",
          type: "text",
          animationConfig: {
            type: "bounce",
            duration: 30,
            animationDirection: "top",
          },
          text: "FLUFFY FRIEND",
          fontSize: 70,
          fontFamily: "Montserrat",
          fontWeight: 900,
          fontColor: "#f3d250",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "left",
          x: 100,
          y: 100,
          stroke: {
            enabled: true,
            color: "#5da2d5",
            width: 5,
            join: "round",
          },
        },
        {
          id: "9-hashtags",
          type: "text",
          x: 100,
          animationConfig: {
            type: "flash",
            duration: 35,
          },
          text: "#meow #kittens #aww",
          fontSize: 24,
          fontFamily: "Roboto",
          fontWeight: 400,
          fontColor: "#ffffff",
          fontStyle: "normal",
          fontVariant: "normal",
          textAlign: "center",
          layout: "center",
          y: 440,
        },
      ],
      media: {
        id: "9",
        type: "video",
        volume: 0.5,
        muted: false,
        transitionConfig: {
          type: "slide",
          direction: "from-right",
          duration: 40,
        },
        url: "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_5MB.mp4",
      },
    },
  ],
};

export const DURATION_IN_FRAMES = 200;
export const VIDEO_WIDTH = 1280;
export const VIDEO_HEIGHT = 720;
export const VIDEO_FPS = 30;

// Base aspect ratio dimensions at 1080p
export const ASPECT_RATIO_LOOKUP = {
  "9:16": {
    width: 1080,
    height: 1920,
  },
  "16:9": {
    width: 1920,
    height: 1080,
  },
  "4:3": {
    width: 1080,
    height: 720,
  },
  "1:1": {
    width: 1080,
    height: 1080,
  },
  "21:9": {
    width: 1080,
    height: 432,
  },
};

// Resolution heights lookup
export const RESOLUTION_HEIGHTS = {
  "1080p": 1080,
  "720p": 720,
  "480p": 480,
  "360p": 360,
};

// Calculate dimensions based on aspect ratio and resolution
export const calculateDimensions = (
  aspectRatio: keyof typeof ASPECT_RATIO_LOOKUP,
  resolution: keyof typeof RESOLUTION_HEIGHTS,
) => {
  const baseAspectRatio = ASPECT_RATIO_LOOKUP[aspectRatio];
  const targetHeight = RESOLUTION_HEIGHTS[resolution];

  // For vertical videos (9:16), base the calculation on width
  if (aspectRatio === "9:16") {
    const scaleFactor = targetHeight / baseAspectRatio.height;
    const width = Math.round(baseAspectRatio.width * scaleFactor);
    return {
      width,
      height: targetHeight,
    };
  }
  // For square videos (1:1), keep width and height equal
  else if (aspectRatio === "1:1") {
    return {
      width: targetHeight,
      height: targetHeight,
    };
  }
  // For all other aspect ratios, calculate width based on original ratio
  else {
    const aspectRatioValue = baseAspectRatio.width / baseAspectRatio.height;
    const width = Math.round(targetHeight * aspectRatioValue);
    return {
      width,
      height: targetHeight,
    };
  }
};
